version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@vue/cli-plugin-router"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
